### ISSUE TITLE
Use outside of Go

### ISSUE THREAD

**Issue by freyacodes** [mavolin/dismock#39]
Hi!

I am working on developing some tools to use Dismock with a Discord library that is not go, more specifically JDA. Probably with a Go application that wraps around Dismock and exposes some control HTTP endpoints.

I'm struggling to understand how Dismock works, and if it will even support my use-cases. I was hoping you could answer my questions:

1. Will Dismock allow me to receive gateway events like message create and slash command invocations?  I was not able to find methods for this. If not, this is all rather moot.
2. The instructions for discordgo say to "disable the state". What does this mean, and is it relevant for what I am doing?
3. When I create a mocker I always get code 404 when accessing its server. I have tried `/oauth2/applications/@me` and `/gateway` with and without the `/api` prefix.

Be warned that I have all of 2 hours of experience with Go.

**Comment by mavolin** [comment]
Hey!

I'll cut right to the chase:

1. Dismock can't mock gateway events. Arikawa (and I believe also discordgo, although don't quote me on that) have exposed (public) methods triggering the event handler ([this would be arikawa's method for that](https://pkg.go.dev/github.com/diamondburned/arikawa/v3@v3.1.0/utils/handler#Handler.Call)). Normally, that method is called by the gateway handler each time it receives an event, but since it's exposed it can also be used directly in a test to mock gateway events. Maybe JDA has a similar functionality you could use.
2. Disabling the state means disabling the cache. This is necessary so that when requesting an otherwise cached entity, such as a `User`, `Guild`, etc, dismock's mock server is hit with the request and the entity is not simply taken from the cache. Otherwise, dismock would have no way of "knowing" whether that entity has been request, nor be able to send the mocked data.
3. Are you making calls to the correct IP and port? You can get the IP and port using `dismock.Mocker.Server.Listener.Addr().String()` (c.f. `net.Listner`'s [docs](https://pkg.go.dev/net#Addr)).
Additionally, you must also register any request you make to the mock server with the mocker, otherwise the mock server will [return 404 as well](https://github.com/mavolin/dismock/blob/v3/pkg/dismock/dismock.go#L120):
```go
m.SendText(discord.Message{
    // the doc of every mock specifies what fields are required, all other
    // fields not relevant to your test can be omitted
    ChannelID: channelID,
    Content: "🏓",
})
```
The above would tell the mocker (`m`) to expect a `POST` request to  `"api/v9/channels/" + channelID + "/messages"` with the content set to ` "🏓"`, which will then return a JSON payload with `channel_id` and `content` set.
If it doesn't receive such a request before the test ends, it will fail the test.

I hope this helps, if you have any more questions feel free to ask.

**Comment by freyacodes** [comment]
Thanks for your quick response

It seems that Dismock works very differently from what we need. I was hoping to be able to generate throwaway stateful guilds and being able to observe the response to, for instance, a command invocation. With the way Dismock is made we would have to configure each endpoint, and that would require extensive bindings as we're not testing from Go. It would also be especially tricky with how our infrastructure is built.

Dismock is still a really cool project though
